package com.demo.models;

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Pack generated by hbm2java
 */
@Entity
@Table(name = "pack")
public class Pack implements java.io.Serializable {

	private Integer id;
	private String name;
	private double price;
	private Set<Invoice> invoices = new HashSet<Invoice>(0);

	public Pack() {
	}

	public Pack(String name) {
		this.name = name;
	}

	public Pack(String name, Set<Invoice> invoices) {
		this.name = name;
		this.invoices = invoices;
	}
	
	

	public Pack(Integer id, String name, double price, Set<Invoice> invoices) {
		super();
		this.id = id;
		this.name = name;
		this.price = price;
		this.invoices = invoices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pack")
	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}

	public double getPrice() {
		return price;
	}

	public void setPrice(double price) {
		this.price = price;
	}
	

}
