package com.demo.models;
// Generated Nov 6, 2023, 11:24:50 AM by Hibernate Tools 4.3.6.Final

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

/**
 * PlaylistSong generated by hbm2java
 */
@Entity
@Table(name = "playlistsong")
public class PlaylistSong implements java.io.Serializable {

	private Integer id;
	private Playlist playlist;
	private Song song;

	public PlaylistSong() {
	}

	public PlaylistSong(Playlist playlist, Song song) {
		this.playlist = playlist;
		this.song = song;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "playlistid", nullable = false)
	public Playlist getPlaylist() {
		return this.playlist;
	}

	public void setPlaylist(Playlist playlist) {
		this.playlist = playlist;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "songid", nullable = false)
	public Song getSong() {
		return this.song;
	}

	public void setSong(Song song) {
		this.song = song;
	}

}
