package com.demo.models;
// Generated Nov 6, 2023, 11:24:50 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import static jakarta.persistence.GenerationType.IDENTITY;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user")
public class User implements java.io.Serializable {

	private Integer id;
	private String fullname;
	private String email;
	private String phone;
	private String username;
	private String password;
	private boolean status;
	private boolean ispremium;
	private String avt;
	private String code;
	private Set<Playlist> playlists = new HashSet<Playlist>(0);
	private Set<Invoice> invoices = new HashSet<Invoice>(0);

	public User() {
	}
	
	public User(Integer id, String fullname, String email, String phone, String username, String password,
			boolean status, boolean ispremium, String avt, String code) {
		super();
		this.id = id;
		this.fullname = fullname;
		this.email = email;
		this.phone = phone;
		this.username = username;
		this.password = password;
		this.status = status;
		this.ispremium = ispremium;
		this.avt = avt;
		this.code = code;
	}

	public User(Integer id, String fullname, String email, String phone, String username, String password,
			boolean status, boolean ispremium, String avt, String code, Set<Playlist> playlists,
			Set<Invoice> invoices) {
		super();
		this.id = id;
		this.fullname = fullname;
		this.email = email;
		this.phone = phone;
		this.username = username;
		this.password = password;
		this.status = status;
		this.ispremium = ispremium;
		this.avt = avt;
		this.code = code;
		this.playlists = playlists;
		this.invoices = invoices;
	}

	public User(String fullname, String email, String phone, String username, String password, boolean status,
			boolean ispremium) {
		this.fullname = fullname;
		this.email = email;
		this.phone = phone;
		this.username = username;
		this.password = password;
		this.status = status;
		this.ispremium = ispremium;
	}

	public User(String fullname, String email, String phone, String username, String password, boolean status,
			boolean ispremium, Set<Playlist> playlists, Set<Invoice> invoices) {
		this.fullname = fullname;
		this.email = email;
		this.phone = phone;
		this.username = username;
		this.password = password;
		this.status = status;
		this.ispremium = ispremium;
		this.playlists = playlists;
		this.invoices = invoices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "fullname", nullable = true, length = 200)
	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	@Column(name = "email", nullable = false, length = 200)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", nullable = true, length = 10)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "username", nullable = true, length = 200)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 200)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}
		
	@Column(name = "avt", nullable = true, length = 200)
	public String getAvt() {
		return avt;
	}

	public void setAvt(String avt) {
		this.avt = avt;
	}

	@Column(name = "code", nullable = false, length = 200)
	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "ispremium", nullable = false)
	public boolean isIspremium() {
		return this.ispremium;
	}

	public void setIspremium(boolean ispremium) {
		this.ispremium = ispremium;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Playlist> getPlaylists() {
		return this.playlists;
	}

	public void setPlaylists(Set<Playlist> playlists) {
		this.playlists = playlists;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Invoice> getInvoices() {
		return this.invoices;
	}

	public void setInvoices(Set<Invoice> invoices) {
		this.invoices = invoices;
	}

}
